apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base/argo-cd-issuer.yaml
- base/argo-cd-certificate.yaml
- base/argo-cd-ui-ingress.yaml
- base/jenkins-ingress.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/ha/install.yaml


patchesStrategicMerge:
- overlays/production/argo-cd-cm.yaml
- overlays/production/argocd-server-service.yaml
- overlays/production/argocd-repo-server-deploy.yaml

patchesJson6902:
- path: overlays/production/argocd-server-deploy-command.yaml
  target:
    group: apps
    kind: Deployment
    name: argocd-server
    version: v1

namespace: argocd

images:
- name: argoproj/argocd
  newName: docker.pkg.github.com/vathsalashetty25/repo-for-images/argocd
  newTag: 1.9.0-24f52b64
- name: quay.io/argoproj/argocd
  newName: docker.pkg.github.com/argoproj/argo-cd/argocd
  newTag: 1.9.0-d8cb02bd
